services:
  ddns:
    container_name: 'ddns'
    build: '.'
    init: true
    image: 'draenal/ddns'
    restart: 'unless-stopped'
    environment:
      SUBZONE: 'local'
      ZONE: 'michaelcook.dev'
      API_KEY_FILE: '/run/secrets/apikey'
    secrets:
      - 'apikey'

secrets:
  apikey:
    file: 'apikey.txt'
