services:
  ddns:
    container_name: 'ddns'
    build: '.'
    restart: 'unless-stopped'
    environment:
      HOSTNAME: 'local'
      ZONE: 'michaelcook.dev'
      API_KEY_FILE: '/run/secrets/apikey'

secrets:
  apikey:
    file: 'apikey.txt'
