services:
  pihole:
    container_name: 'pihole'
    image: 'pihole/pihole:latest'
    hostname: 'ph2'
    volumes:
      - '/home/mike/homelab/pve1/dns/pi-hole/config:/etc/pihole'
      - './config/dnsmasq.d:/etc/dnsmasq.d'
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD_FILE: '/run/secrets/password'
      DNSMASQ_LISTENING: 'local'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001'
      FTLCONF_LOCAL_IPV4: '192.168.1.54'
      PIHOLE_DOMAIN: 'local.michaelcook.dev'
      DNS_FQDN_REQUIRED: true
      DNS_BOGUS_PRIV: true
    cap_add:
      - 'NET_ADMIN'
    network_mode: 'host'
    secrets:
      - 'password'
    restart: 'unless-stopped'

secrets:
  password:
    file: 'password.txt'
