include:
  - './docker-networks.yaml'

services:
  postgresql:
    image: 'docker.io/library/postgres:12-alpine'
    container_name: 'postgresql'
    environment:
      POSTGRES_PASSWORD_FILE: '/run/secrets/postgres-password'
      POSTGRES_USER: 'homelab'
      POSTGRES_DB: 'homelab'
    secrets:
      - 'postgres-password'
    volumes:
      - '/home/mike/homelab/pve1/paladin/postgresql/data:/var/lib/postgresql/data'
    networks:
      - 'authentik'
    restart: 'unless-stopped'

secrets:
  postgres-password:
    file: 'password.txt'
