services:
  postgresql:
    image: 'docker.io/library/postgres:12-alpine'
    container_name: 'postgresql'
    environment:
      POSTGRES_PASSWORD_FILE: '/run/secrets/postgres-password'
      POSTGRES_USER: 'homelab'
      POSTGRES_DB: 'homelab'
    secrets:
      - 'postgres-password'
    volumes:
      - 'database:/var/lib/postgresql/data'
    network_mode: 'bridge'
    restart: 'unless-stopped'

secrets:
  postgres-password:
    file: 'password.txt'