services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:v2.11.8'
    restart: 'unless-stopped'
    security_opt:
      - 'no-new-privileges:true'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    environment:
      CF_DNS_API_TOKEN_FILE: '/run/secrets/dnsapitoken'
    secrets:
      - 'dnsapitoken'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/home/mike/homelab/pve1/infrastructure/traefik/traefik.yaml:/traefik.yaml:ro'
      - '/home/mike/homelab/pve1/infrastructure/traefik/config:/config:ro'
      - '/home/mike/homelab/pve1/infrastructure/traefik/acme.json:/acme.json'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=mike:$$apr1$26u9afvb$$M.WjHBpcVYSfvBnR2cmtg.'
      - 'traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https'
      # traefik dashboard
      - 'traefik.http.routers.traefik.rule=Host(`traefik.local.michaelcook.dev`)'
      - 'traefik.http.routers.traefik.entrypoints=http'
      - 'traefik.http.routers.traefik.middlewares=traefik-https-redirect'
      # traefik dashboard SSL
      - 'traefik.http.routers.traefik-secure.rule=Host(`traefik.local.michaelcook.dev`)'
      - 'traefik.http.routers.traefik-secure.entrypoints=https'
      - 'traefik.http.routers.traefik-secure.middlewares=traefik-auth'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.traefik-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].main=local.michaelcook.dev'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.michaelcook.dev'
      - 'traefik.http.routers.traefik-secure.tls.domains[1].main=michaelcook.dev'
      - 'traefik.http.routers.traefik-secure.tls.domains[1].sans=*.michaelcook.dev'
      - 'traefik.http.routers.traefik-secure.service=api@internal'
    network_mode: 'bridge'

secrets:
  dnsapitoken:
    file: 'dnsapitoken.txt'
