include:
  - '../postgresql/docker-compose.yaml'
  - '../redis/docker-compose.yaml'

services:
  authentik-server:
    image: 'ghcr.io/goauthentik/server:2023.10.7'
    container_name: 'authentik-server'
    command: 'server'
    environment:
      AUTHENTIK_REDIS__HOST: 'redis'
      AUTHENTIK_POSTGRESQL__HOST: 'postgresql'
      AUTHENTIK_POSTGRESQL__USER: 'homelab'
      AUTHENTIK_POSTGRESQL__NAME: 'homelab'
      AUTHENTIK_POSTGRESQL__PASSWORD: 'file:///run/secrets/postgres-password'
      AUTHENTIK_SECRET_KEY: 'file:///run/secrets/authentik-secret-key'
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
    volumes:
      - './media:/media'
      - './custom-templates:/templates'
    ports:
      - '9000:9000'
      - '9443:9443'
    secrets:
      - 'postgres-password'
      - 'authentik-secret-key'
    depends_on:
      - 'postgresql'
      - 'redis'
    network_mode: 'bridge'
    restart: 'unless-stopped'
  authentik-worker:
    image: 'ghcr.io/goauthentik/server:2023.10.7'
    container_name: 'authentik-worker'
    command: 'worker'
    environment:
      AUTHENTIK_REDIS__HOST: 'redis'
      AUTHENTIK_POSTGRESQL__HOST: 'postgresql'
      AUTHENTIK_POSTGRESQL__USER: 'homelab'
      AUTHENTIK_POSTGRESQL__NAME: 'homelab'
      AUTHENTIK_POSTGRESQL__PASSWORD: 'file:///run/secrets/postgres-password'
      AUTHENTIK_SECRET_KEY: 'file:///run/secrets/authentik-secret-key'
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    secrets:
      - 'postgres-password'
      - 'authentik-secret-key'
    depends_on:
      - postgresql
      - redis
    network_mode: 'bridge'
    restart: 'unless-stopped'

secrets:
  authentik-secret-key:
    file: 'secret.txt'

volumes:
  database:
    driver: local
  redis:
    driver: local