http:
  routers:
    pve1:
      entrypoints:
        - 'https'
      rule: 'Host(`pve1.local.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'pve1'
    ph1:
      entrypoints:
        - 'https'
      rule: 'Host(`ph1.local.michaelcook.dev`)'
      middlewares:
        - 'pihole-redirectregex'
        - 'default-headers'
        - 'pihole-addprefix'
        - 'https-redirect'
      tls: {}
      service: 'ph1'
    ph2:
      entrypoints:
        - 'https'
      rule: 'Host(`ph2.local.michaelcook.dev`)'
      middlewares:
        - 'pihole-redirectregex'
        - 'default-headers'
        - 'pihole-addprefix'
        - 'https-redirect'
      tls: {}
      service: 'ph2'
    portainer:
      entrypoints:
        - 'https'
      rule: 'Host(`portainer.local.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'portainer'
    foundry:
      entrypoints:
        - 'https'
      rule: 'Host(`foundry.local.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'foundry'
    foundry-external:
      entrypoints:
        - 'https'
      rule: 'Host(`foundry.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'foundry'
    ddb-importer:
      entrypoints:
        - 'https'
      rule: 'Host(`ddb-importer.local.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'ddb-importer'
    gateway:
      entrypoints:
        - 'https'
      rule: 'Host(`gateway.local.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'gateway'
    authentik:
      entrypoints:
        - 'https'
      rule: 'Host(`authentik.local.michaelcook.dev`)'
      middlewares:
        - 'default-headers'
        - 'https-redirect'
      tls: {}
      service: 'authentik'
  services:
    pve1:
      loadBalancer:
        servers:
          - url: 'https://192.168.1.100:8006'
        passHostHeader: true
    ph1:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.53:80'
        passHostHeader: true
    ph2:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.54:80'
        passHostHeader: true
    portainer:
      loadBalancer:
        servers:
          - url: 'https://192.168.1.102:9443'
        passHostHeader: true
    foundry:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.105:30000'
        passHostHeader: true
    ddb-importer:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.105:30001'
        passHostHeader: true
    gateway:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.1:80'
    authentik:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.200:9443'
  middlewares:
    pihole-addprefix:
      addPrefix:
        prefix: "/admin"

    pihole-redirectregex:
      redirectRegex:
        regex: "/admin/(.*)"
        replacement: /

    https-redirect:
      redirectScheme:
        scheme: 'https'

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNoSniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: 'SAMEORIGIN'
        customRequestHeaders: 
          X-Forwarded-Proto: 'https'

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - '192.168.0.0/16'

    secured:
      chain:
        middlewares:
          - 'default-whitelist'
          - 'default-headers'