services:
  redis:
    image: 'docker.io/library/redis:alpine'
    container_name: 'redis'
    command: '--save 60 1 --loglevel warning'
    volumes:
      - 'redis:/data'
    network_mode: 'bridge'
    restart: 'unless-stopped'

volumes:
  redis:
    driver: local