services:
  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - './garage.toml:/etc/garage.toml'
      - './meta:/var/lib/garage/meta'
      - './data:/var/lib/garage/data'
    restart: unless-stopped
  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    volumes:
      - './garage.toml:/etc/garage.toml:ro'
    ports:
      - 3909:3909
    environment:
      S3_ENDPOINT_URL: http://garage:3900
      API_BASE_URL: http://garage:3903
    restart: unless-stopped