FROM alpine:3.18.4

RUN apk add --no-cache curl jq busybox-openrc

COPY ./entrypoint.sh /entrypoint.sh

COPY ./ddns.sh /ddns.sh
RUN chmod 0744 /ddns.sh

RUN which crond
RUN rm -rf /etc/periodic

# TODO: run as a user other than root
# https://medium.com/@geekidea_81313/running-cron-jobs-as-non-root-on-alpine-linux-e5fa94827c34
RUN echo '*/1 * * * * /ddns.sh' > /var/spool/cron/crontabs/root

ENTRYPOINT ["/entrypoint.sh"]
CMD ["crond", "-f", "-l", "2"]