services:
  foundry_vtt:
    container_name: 'foundryvtt'
    image: 'felddy/foundryvtt:release'
    ports:
      - '30000:30000/tcp'
    environment:
      FOUNDRY_HOSTNAME: 'foundry.michaelcook.dev'
      FOUNDRY_LOCAL_HOSTNAME: 'foundry.local.michaelcook.dev'
      FOUNDRY_MINIFY_STATIC_FILES: true
      FOUNDRY_TELEMETRY: true
      FOUNDRY_VERSION: '11.313'
      FOUNDRY_PROXY_SSL: true
      FOUNDRY_PROXY_PORT: 443
    volumes:
      - '/root/foundryvtt/data:/data'
    secrets:
      - source: 'config'
        target: 'config.json'
    network_mode: 'bridge'
    restart: 'unless-stopped'

  ddb_importer:
    container_name: 'ddb-importer'
    image: ghcr.io/mrprimate/ddb-proxy:latest
    ports:
      - '30001:3000/tcp'
    network_mode: 'bridge'
    restart: 'unless-stopped'

secrets:
  config:
    file: 'secrets.json'
